# Site settings
title: Eljo Pleqi # site title
description: >- # site description
  I am a Web Developer and UI/UX Designer
  Graduated from Le Wagon in Cologne batch 890 for web development in Le Wagon bootcamp.
  After working in marketing and advertising for 7 years and diving deep into digital marketing, leading tech and creative teams I realised it was time for a change. 
  I took the decision to follow my passion for web development and tech in general as wanted a more hands on role in terms of building software.
lang: en-US # default lang
timezone: Europe/Berlin # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/EljoPleqi/eljopleqi.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Eljo Pleqi # author name
  bio: >- # tell to the world
    I am a Web Developer and UI/UX Designer
    Graduated from Le Wagon in Cologne batch 890 for web development in Le Wagon bootcamp.
    After working in marketing and advertising for 7 years and diving deep into digital marketing, leading tech and creative teams I realised it was time for a change.  
    meet me at <a href="https://www.linkedin.com/in/eljopleqi/" target="_blank" rel="noopener">LinkedIn</a>, 
    <a href="https://twitter.com/Eljo_Pleqi" target="_blank" rel="noopener">Twitter</a>
    and <a href="https://github.com/EljoPleqi" target="_blank" rel="noopener">Github</a>.

  github: EljoPleqi # github username
  twitter: Eljo_Pleqi # twitter username
  linkedin: eljopleqi # twitter username
  email: eljopleqi@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: https://eljopleqi.github.io/ #
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
